services:
  postgres:
    image: postgres:17
    container_name: ttrpg_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: inz12345
      POSTGRES_DB: ttrpg_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # optional, so you can connect from local tools like pgAdmin
    healthcheck: #
      test: ["CMD-SHELL", "pg_isready -U postgres -d ttrpg_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  backend-api:
    build:
      context: ./src/backend/TtrpgHelperBackend
      dockerfile: TtrpgHelperBackend/Dockerfile

    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ttrpg_db;Username=postgres;Password=inz12345
    depends_on:
          postgres: 
            condition: service_healthy
      

  frontend-app:
    build:
      context: ./src/frontend/vue-ttrpg-front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080 # <-- NEW VITE/VUE VARIABLE
    depends_on:
      - backend-api
    volumes:
      - ./src/frontend/vue-ttrpg-front:/app
      - /app/node_modules

volumes:
  pg_data: